seed_everything: 3407  # https://arxiv.org/abs/2109.08203
trainer:
  accelerator: mps
  devices: 1
  precision: bf16-mixed
  fast_dev_run: true
  max_steps: 30000 #500000
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        verbose: true
        save_top_k: 1
        save_last: true
        monitor: val_loss
        mode: min

model:
  model_name: google/byt5-small
  lr: 5e-4
  warmup_steps: 2000
  num_beams: 1
  length_penalty: 0.0
  eval_num_retrieved: 100
  eval_num_workers: 1  # Lower this number if you don't have 80GB GPU memory. <-- 5
  eval_num_gpus: 1
  eval_num_theorems: 100  # Lower this number will make validation faster (but noiser). <-- 250

data:
  data_path: /Users/artem.semidetnov/Desktop/MetaGenerator_v1/dataset/
  batch_size: 3  # effective_batch_size == batch_size * accumulate_grad_batches * devices
  eval_batch_size: 64
  max_inp_seq_len: 512
  max_oup_seq_len: 128
  p_drop: 0.5
  num_workers: 2
